### ISSUE TITLE
Cannot start client docker-compose.yaml

### ISSUE THREAD

**Issue by wakame-tech** [i-pu/ipu#19]
I run this command at client directory but cannot start...
```
docker-compose up --build
```

this is logs. 
```
web_1  | 
web_1  | > client-ts@0.1.0 serve /app
web_1  | > vue-cli-service serve
web_1  | 
web_1  | module.js:549
web_1  |     throw err;
web_1  |     ^
web_1  | 
web_1  | Error: Cannot find module '@vue/cli-plugin-e2e-cypress'
web_1  |     at Function.Module._resolveFilename (module.js:547:15)
web_1  |     at Function.Module._load (module.js:474:25)
web_1  |     at Module.require (module.js:596:17)
web_1  |     at require (internal/module.js:11:18)
web_1  |     at idToPlugin (/app/node_modules/@vue/cli-service/lib/Service.js:138:14)
web_1  |     at Object.keys.concat.filter.map.id (/app/node_modules/@vue/cli-service/lib/Service.js:178:20)
web_1  |     at Array.map (<anonymous>)
web_1  |     at Service.resolvePlugins (/app/node_modules/@vue/cli-service/lib/Service.js:164:10)
web_1  |     at new Service (/app/node_modules/@vue/cli-service/lib/Service.js:34:25)
web_1  |     at Object.<anonymous> (/app/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17)
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! client-ts@0.1.0 serve: `vue-cli-service serve`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR! 
web_1  | npm ERR! Failed at the client-ts@0.1.0 serve script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1  | 
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2019-05-03T14_15_22_419Z-debug.log
```

**Comment by wakame-tech** [comment]
In my environment, there is nothing in running `docker-compose up --build`.
pls
```
git pull origin master && cd client && docker-compose down && docker-compose up --build
```
again. (building takes about 10minutes ... )
If the error occurs again, I'll check more.

**Comment by wakame-tech** [comment]
Resolved ✨
https://github.com/i-pu/ipu/commit/791427ccc0d368672cb2da9ea486a7f1d96f6a0d
