### ISSUE TITLE
Cypress in Docker

### ISSUE THREAD

**Issue by wakame-tech** [i-pu/ipu#20]
# Overview
An error occured in a Dcoker container when run `yarn test:e2e`.

# Todo
<https://docs.cypress.io/examples/examples/docker.html#Images>

# Logs
```
/app # yarn test:e2e
...
It looks like this is your first time using Cypress: 3.2.0

 ✖  Verifying Cypress can run /root/.cache/Cypress/3.2.0/Cypress
   → Cypress Version: 3.2.0
Your system is missing the dependency: XVFB

Install XVFB and run Cypress again.

Read our documentation on dependencies for more information:

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Caught error trying to run XVFB: "Your system is missing the dependency: XVFB

Install XVFB and run Cypress again.

Read our documentation on dependencies for more information:

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Error: spawn Xvfb ENOENT
----------

Platform: linux (Raspbian - )
Cypress Version: 3.2.0"
----------

Platform: linux (Raspbian - )
Cypress Version: 3.2.0
 ERROR  Error: Command failed: /app/node_modules/cypress/bin/cypress open --config baseUrl=http://localhost:8081/
Error: Command failed: /app/node_modules/cypress/bin/cypress open --config baseUrl=http://localhost:8081/
    at makeError (/app/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/app/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/app # npx cypress run
It looks like this is your first time using Cypress: 3.2.0

 ✖  Verifying Cypress can run /root/.cache/Cypress/3.2.0/Cypress
   → Cypress Version: 3.2.0
Your system is missing the dependency: XVFB

Install XVFB and run Cypress again.

Read our documentation on dependencies for more information:

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Caught error trying to run XVFB: "Your system is missing the dependency: XVFB

Install XVFB and run Cypress again.

Read our documentation on dependencies for more information:

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

Error: spawn Xvfb ENOENT
----------

Platform: linux (Raspbian - )
Cypress Version: 3.2.0"
----------

Platform: linux (Raspbian - )
Cypress Version: 3.2.0
```

**Comment by hamadakafu** [comment]
何回かやったらなんか動いたから閉じてもok

**Comment by wakame-tech** [comment]
thx
